# Maven

# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'pipelines-devops-exercise-docker'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: './my-app/pom.xml'    
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: true
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
    goals: 'package'

- task: CmdLine@2
  inputs:
    script: |      
      pwd
      ls -l   
- task: Docker@2
  inputs:
    containerRegistry: 'DockerHubGilad'
    repository: 'devopsworkking/devops_exercise'
    command: 'buildAndPush'
    Dockerfile: 'DockerFile'

- task: CmdLine@2
  inputs:
    script: |
      docker run devopsworkking/devops_exercise
